kind: pipeline

steps:
  - name: build a docker image
    image: docker
    environment:
      DOCKER_NAME:
        from_secret: docker_name
    commands:
      - echo ${DOCKER_NAME}
      - docker build -t $${DOCKER_NAME} .
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
