kind: pipeline

steps:
  - name: build a docker image
    image: docker
    environment:
      DOCKER_IMAGE_NAME:
        from_secret: docker_image_name
    commands:
      - echo $${DOCKER_IMAGE_NAME}
      - docker build -t $${DOCKER_IMAGE_NAME} .
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

volumes:
  - name: docker_socket
    host:
      path: /var/r