kind: pipeline

steps:
  - name: build a docker image
    image: docker
    commands:
      - docker build -t $${DOCKER_NAME} .
    secrets: [ docker_name ]
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
