kind: pipeline

steps:
  - name: Build image
    image: docker
    environment:
      DOCKER_IMAGE_NAME:
        from_secret: docker_image_name
    commands:
      - docker build -t $${DOCKER_IMAGE_NAME} .
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
  - name: Tag image
    image: docker
    environment:
      DOCKER_IMAGE_NAME:
        from_secret: docker_image_name
    commands:
      - docker tag $${DOCKER_IMAGE_NAME} $${DOCKER_IMAGE_NAME}:latest
      - docker tag $${DOCKER_IMAGE_NAME} $${DOCKER_IMAGE_NAME}:${CI_BUILD_NUMBER}
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
  - name: Push image
    image: docker
    environment:
      DOCKER_IMAGE_NAME:
        from_secret: docker_image_name
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
      - docker push $${DOCKER_IMAGE_NAME}
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
  - name: Clean Docker Cache
    image: docker
    commands:
      - docker system prune -f
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock
