kind: pipeline

steps:
    - name: docker  
      image: plugins/docker
      privileged: true
      settings:
        repo: lacquerlabs/pythonproxy
        tags: latest
        username:
          from_secret: docker_username
        password:
          from_secret: docker_password
