version: '3.5'
services:
  pythonproxy:
    container_name: pythonproxy
    image: lacquerlabs/pythonproxy:latest
    restart: "no"
    ports:
      - "3141:3141"
    volumes:
      - ${PWD}/persistent:/app/server
    environment:
      - SERVER_THREADS=16
    labels:
      - traefik.enable=false
